<h2> ** TensorFlow **</h2>

<h4> Hello world! in tensorflow </h4>

In [1]:
import tensorflow as tf

In [2]:
a= tf.constant("Hello")
b= tf.constant("World")

In [3]:
c= tf.add(a,b)


In [4]:
session = tf.Session()

In [5]:
result = session.run(c)
print(result)


b'HelloWorld'


In [6]:
session.close()

<h4> Matrix Multiplication in TensorFlow </h4>

In [7]:
matrix_one = tf.constant([[1,2,3],[4,5,6]])
matrix_two = tf.constant([[1,2,3],[4,5,6]])
matrix_3 = tf.constant([[1,2],[3,4],[5,6]])
first_op = tf.add(matrix_one,matrix_two)
second_op = matrix_one + matrix_two

mul_op = tf.matmul(matrix_one,matrix_3)

with tf.Session() as session:
    result=session.run(first_op)
    print(result)
    result=session.run(second_op)
    print(result)
    result = session.run(mul_op)
    print(result)

[[ 2  4  6]
 [ 8 10 12]]
[[ 2  4  6]
 [ 8 10 12]]
[[22 28]
 [49 64]]
