In [47]:
import tensorflow as tf

In [35]:
a= tf.constant(1)
b= tf.constant(2)

In [36]:
c= tf.add(a,b)


In [37]:
session = tf.Session()

In [38]:
result = session.run(c)
print(result)
m=tf.device(c)
print(m)

3


In [39]:
session.close()

In [40]:
print(result)

3


In [50]:
matrix_one = tf.constant([[1,2,3],[4,5,6]])
matrix_two = tf.constant([[1,2,3],[4,5,6]])
matrix_3 = tf.constant([[1,2],[3,4],[5,6]])
first_op = tf.add(matrix_one,matrix_two)
second_op = matrix_one + matrix_two

mul_op = tf.matmul(matrix_one,matrix_3)

with tf.Session() as session:
    result=session.run(first_op)
    print(result)
    result=session.run(second_op)
    print(result)
    result = session.run(mul_op)
    print(result)

[[ 2  4  6]
 [ 8 10 12]]
[[ 2  4  6]
 [ 8 10 12]]
[[22 28]
 [49 64]]
