<h2> ** TensorFlow **</h2>

<h4> Hello world! in tensorflow </h4>

In [44]:
import tensorflow as tf
import numpy as np

In [45]:
a= tf.constant("Hello")
b= tf.constant("World")

In [46]:
c= tf.add(a,b)


In [47]:
session = tf.Session()

In [48]:
result = session.run(c)
print(result)


b'HelloWorld'


In [49]:
session.close()

<h4> Matrix Multiplication in TensorFlow </h4>

In [50]:
matrix_one = tf.constant([[1,2,3],[4,5,6]])
matrix_two = tf.constant([[1,2,3],[4,5,6]])
matrix_3 = tf.constant([[1,2],[3,4],[5,6]])
first_op = tf.add(matrix_one,matrix_two)
second_op = matrix_one + matrix_two

mul_op = tf.matmul(matrix_one,matrix_3)

with tf.Session() as session:
    result=session.run(first_op)
    print(result)
    result=session.run(second_op)
    print(result)
    result = session.run(mul_op)
    print(result)

[[ 2  4  6]
 [ 8 10 12]]
[[ 2  4  6]
 [ 8 10 12]]
[[22 28]
 [49 64]]


<h4>Typical flow of a tensorflow project :</h4>

1- creating a graph - tf.constant , tf.variable, tf.placeholder , tf.nn.sigmoid 

2- executing the graph (within a session)

3- for visualisation - Tensorboard

<h4> PlaceHolder In tensorflow </h4>
1- allows reusability

2-different data can be used every time when we run the graph(feed_dict)

In [51]:
x = tf.placeholder(tf.float32,name='X',shape=(4,4))
w = tf.placeholder(tf.float32, name='W',shape=(4,1))
b = tf.fill((4,1), 1.0 , name='bias')
            
y = tf.add(tf.matmul(x,w),b)

m = tf.reduce_max(y)

In [52]:
x_data= np.random.randn(4,4)
w_data = np.random.randn(4,1)


In [53]:
with tf.Session() as sess:
    
    output = sess.run(m , feed_dict={x:x_data , y:w_data})
    print(output)
    
    

0.670581


<h4> Implementing a simple neural network using tensorflow </h4>

In [54]:
# X,W,b,Y

x = tf.placeholder(tf.float32 , shape=(1,3))
y_true = tf.placeholder(tf.float32 , shape=(1,1))
w = tf.Variable([[0,0,0]], dtype= tf.float32, name='W')
b = tf.Variable(0,dtype=tf.float32,name ='bias')

#output

y_pred = tf.matmul(w,tf.transpose(x)) + b

In [55]:
#MSE (mean squared error)

loss = tf.reduce_mean(tf.square(y_pred-y_true))

#Cross entropy

loss = tf.nn.sigmoid_cross_entropy_with_logits(labels=y_true , logits=y_pred)
loss = tf.reduce_mean(loss)

In [62]:

import numpy as np

x_data = np.random.randn(2000,3)
w_real = [0.4, 0.6, 0.2]
b_real = -0.3 
noise = np.random.randn(1,2000)*0.1 
y_data = np.matmul(w_real, x_data.T)+b_real+noise

In [63]:
num_iterations = 10
graph = tf.Graph()
wb_append = []

with graph.as_default():
    x = tf.placeholder(tf.float32 , shape=[None,3])
    y_true = tf.placeholder(tf.float32 ,shape=None)
    
    with tf.name_scope('main') as scope:
        w = tf.Variable([[0,0,0]],dtype=tf.float32,name='W')
        b = tf.Variable([0],dtype=tf.float32,name='bias')
        y_pred = tf.matmul(w,tf.transpose(x))+b
        
    with tf.name_scope('loss') as scope:
        loss = tf.reduce_mean(tf.square(y_pred - y_true))
        
    with tf.name_scope('training') as scope:
        learning_rate = 0.5
        optimizer = tf.train.GradientDescentOptimizer(learning_rate)
        train = optimizer.minimize(loss)
    
    
    initialize = tf.global_variables_initializer()
    
    with tf.Session() as session:
        session.run(initialize)
        for step in range(num_iterations):
            session.run(train, feed_dict={x:x_data,y_true:y_data})
            if(step % 5 ==0):
                print(step,session.run([w,b]))
                wb_append.append(session.run([w,b]))

0 [array([[ 0.37931877,  0.58414686,  0.1970274 ]], dtype=float32), array([-0.27091694], dtype=float32)]
5 [array([[ 0.39990082,  0.59435117,  0.2001024 ]], dtype=float32), array([-0.29942051], dtype=float32)]
