<h2> ** TensorFlow **</h2>

<h4> Hello world! in tensorflow </h4>

In [14]:
import tensorflow as tf
import numpy as np

In [2]:
a= tf.constant("Hello")
b= tf.constant("World")

In [3]:
c= tf.add(a,b)


In [4]:
session = tf.Session()

In [5]:
result = session.run(c)
print(result)


b'HelloWorld'


In [6]:
session.close()

<h4> Matrix Multiplication in TensorFlow </h4>

In [7]:
matrix_one = tf.constant([[1,2,3],[4,5,6]])
matrix_two = tf.constant([[1,2,3],[4,5,6]])
matrix_3 = tf.constant([[1,2],[3,4],[5,6]])
first_op = tf.add(matrix_one,matrix_two)
second_op = matrix_one + matrix_two

mul_op = tf.matmul(matrix_one,matrix_3)

with tf.Session() as session:
    result=session.run(first_op)
    print(result)
    result=session.run(second_op)
    print(result)
    result = session.run(mul_op)
    print(result)

[[ 2  4  6]
 [ 8 10 12]]
[[ 2  4  6]
 [ 8 10 12]]
[[22 28]
 [49 64]]


<h4>Typical flow of a tensorflow project :</h4>

1- creating a graph - tf.constant , tf.variable, tf.placeholder , tf.nn.sigmoid 

2- executing the graph (within a session)

3- for visualisation - Tensorboard

<h4> PlaceHolder In tensorflow </h4>
1- allows reusability

2-different data can be used every time when we run the graph(feed_dict)

In [19]:
x = tf.placeholder(tf.float32,name='X',shape=(4,4))
w = tf.placeholder(tf.float32, name='W',shape=(4,1))
b = tf.fill((4,1), 1.0 , name='bias')
            
y = tf.add(tf.matmul(x,w),b)

m = tf.reduce_max(y)

In [20]:
x_data= np.random.randn(4,4)
w_data = np.random.randn(4,1)


In [21]:
with tf.Session() as sess:
    
    output = sess.run(m , feed_dict={x:x_data , y:w_data})
    print(output)
    
    

0.276654


In [ ]:
[[ 1.2855438 ]
 [ 1.4726907 ]
 [ 0.64973378]
 [-1.58538783]]